name: qrscanner
description: A QR Scanning application which saves all scanned QR codes and let you copy them whenever you want.

publish_to: "none"

version: 1.0.6+1

environment:
    sdk: ">=2.17.5 <3.0.0"

dependencies:
    another_flushbar: ^1.12.30
    barcode_scan2: ^4.2.4
    cloud_firestore: ^4.8.0
    cupertino_icons: ^1.0.5
    firebase_auth: ^4.6.2
    firebase_core: ^2.13.1
    firebase_storage: ^11.2.2
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    flutter_vibrate: ^1.3.0
    fluttertoast: ^8.2.2
    image_picker: ^0.8.7+5
    package_info_plus: ^4.0.2
    shared_preferences: ^2.1.1
    soundpool: ^2.3.0
    # cupertino_icons: ^1.0.2
    # firebase_core: ^1.18.0
    # firebase_auth: ^3.3.20
    # firebase_storage: ^10.2.18
    # cloud_firestore: ^3.1.18
    # another_flushbar: ^1.10.29
    # fluttertoast: ^8.0.9
    # shared_preferences: ^2.0.15
    # image_picker: ^0.8.5+3
    # soundpool: ^2.3.0
    # barcode_scan2: ^4.2.1
    # flutter_vibrate: ^1.3.0

dev_dependencies:
    build_runner: ^2.4.4
    flutter_gen_runner: ^5.3.1
    flutter_launcher_icons: ^0.13.1
    flutter_lints: ^2.0.1
    flutter_test:
        sdk: flutter

flutter_gen:
    output: lib/gen/
    line_length: 80

    integrations:
        flutter_svg: true

flutter:
    uses-material-design: true
    generate: true

    assets:
        - asset/image/
        - asset/sound/
